<html>
<head>
    <title>Event</title>
</head>
<body>
<p>${eventObject.name}</p>
<p>${eventObject.rating}</p>
<p>${eventObject.basePrice}</p>
<p>${eventObject.auditoriumName}</p>
<p>${eventObject.datesEvent}</p>
</body>
</html>
